### PR TITLE
Fix missing nginx runtime dependency: libyajl

### PR DESCRIPTION
**Pull request by black-roland**
Hi.

This is a fix for nginx error:

```
nginx: error while loading shared libraries: libyajl.so.2: cannot open shared object file: No such file or directory
```

### CODE REVIEW

**Comment by cicku** [comment]
Hi,

Normally this shouldn't be hardcoded into SPEC because RPM detects the dependencies via linker (ld).

Can you run `rpm -qls yajl` and feedback here again?

Thanks.

**Comment by black-roland** [comment]
```
$ rpm -qls yajl
normal        /usr/bin/json_reformat
normal        /usr/bin/json_verify
normal        /usr/lib/libyajl.so.2
normal        /usr/lib/libyajl.so.2.1.0
normal        /usr/share/doc/yajl
normal        /usr/share/doc/yajl/COPYING
normal        /usr/share/doc/yajl/ChangeLog
normal        /usr/share/doc/yajl/README
normal        /usr/share/doc/yajl/TODO
```

Linux 4.1.3-200.fc22.i686+PAE. I use [this Copr repository](https://copr.fedoraproject.org/coprs/mosquito/nginx/).

**Comment by 1dot75cm** [comment]
> because RPM detects the dependencies via linker (ld).

Indeed the case. I need to test it in a fc22.i686 VM.

```
# rpm -qR nginx | grep yajl
libyajl.so.2()(64bit)
```

**Comment by 1dot75cm** [comment]
Hi, @black-roland. I have tested pass. please tell me, how to reproduce. Thanks.

```
# uname -r
4.1.10-200.fc22.i686+PAE
# dnf install nginx
 GeoIP                    i686         1.6.5-1.fc22                      fedora               135 k
 GeoIP-GeoLite-data       noarch       2015.08-1.fc22                    updates              364 k
 apr                      i686         1.5.1-3.fc22                      fedora               118 k
 apr-util                 i686         1.5.4-1.fc22                      fedora                99 k
 fontconfig               i686         2.11.94-4.fc22                    updates              245 k
 gd                       i686         2.1.1-2.fc22                      fedora               145 k
 gperftools-libs          i686         2.4-1.fc22                        fedora               286 k
 libXpm                   i686         3.5.11-3.fc22                     fedora                53 k
 libunwind                i686         1.1-10.fc22                       updates               63 k
 libvpx                   i686         1.3.0-7.fc22                      updates              525 k
 luajit                   i686         2.0.3-4.fc22                      fedora               440 k
 nginx                    i686         1:1.9.5-3.modsec_2.9.0.fc22       mosquito-nginx       3.2 M
 nginx-filesystem         noarch       1:1.9.5-3.modsec_2.9.0.fc22       mosquito-nginx        20 k
 ssdeep-libs              i686         2.13-1.fc22                       fedora                23 k
 yajl                     i686         2.1.0-3.fc22                      fedora                37 k
# rpm -qR nginx | grep yajl
libyajl.so.2
# LD_DEBUG=files nginx -t
1284:   calling init: /lib/libyajl.so.2
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```

**Comment by black-roland** [comment]
I updated from official nginx to mosquito/nginx.

Steps to reproduce:

```
# dnf copr enable mosquito/nginx
# dnf update -y
```

I also tried reinstalling (sorry for russian in console output):

```
# dnf copr disable mosquito/nginx
# dnf remove nginx
# dnf clean all
# dnf copr enable mosquito/nginx
# dnf install nginx
Зависимости разрешены.
=====================================================================================================================================================================================================================
 Пакет                                              Архитектура                              Версия                                                           Репозиторий                                      Размер
=====================================================================================================================================================================================================================
Установка:
 nginx                                              i686                                     1:1.9.5-3.modsec_2.9.0.fc22                                      mosquito-nginx                                   3.2 M
 nginx-filesystem                                   noarch                                   1:1.9.5-3.modsec_2.9.0.fc22                                      mosquito-nginx                                    20 k
 ssdeep-libs                                        i686                                     2.13-1.fc22.remi                                                 remi                                              22 k

Результат операции
=====================================================================================================================================================================================================================
Установка   3 Packages

Объем загрузки: 3.2 M
Объем изменений: 14 M
Продолжить? [д/Н]: y
Загрузка пакетов:
(1/3): ssdeep-libs-2.13-1.fc22.remi.i686.rpm                                                                                                                                         137 kB/s |  22 kB     00:00    
(2/3): nginx-filesystem-1.9.5-3.modsec_2.9.0.fc22.noarch.rpm                                                                                                                          23 kB/s |  20 kB     00:00    
(3/3): nginx-1.9.5-3.modsec_2.9.0.fc22.i686.rpm                                                                                                                                      1.6 MB/s | 3.2 MB     00:02    
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Общий размер                                                                                                                                                                         1.6 MB/s | 3.2 MB     00:02     
Выполнение проверки транзакции
Проверка транзакции успешно завершена.
Идет проверка транзакции
Тест транзакции проведен успешно
Выполнение транзакции
  Установка    : nginx-filesystem-1:1.9.5-3.modsec_2.9.0.fc22.noarch                                                                                                                                             1/3 
  Установка    : ssdeep-libs-2.13-1.fc22.remi.i686                                                                                                                                                               2/3 
  Установка    : nginx-1:1.9.5-3.modsec_2.9.0.fc22.i686                                                                                                                                                          3/3 
warning: /etc/nginx/nginx.conf created as /etc/nginx/nginx.conf.rpmnew
  Проверка     : nginx-1:1.9.5-3.modsec_2.9.0.fc22.i686                                                                                                                                                          1/3 
  Проверка     : nginx-filesystem-1:1.9.5-3.modsec_2.9.0.fc22.noarch                                                                                                                                             2/3 
  Проверка     : ssdeep-libs-2.13-1.fc22.remi.i686                                                                                                                                                               3/3 

Установлено:
  nginx.i686 1:1.9.5-3.modsec_2.9.0.fc22                              nginx-filesystem.noarch 1:1.9.5-3.modsec_2.9.0.fc22                              ssdeep-libs.i686 2.13-1.fc22.remi                             

Выполнено!
```

`libyajl.so.2` shown in the package dependencies, but not installs automaticaly. Maybe this is DNF bug?

```
# rpm -qR nginx | grep yajl
libyajl.so.2
```

**Comment by black-roland** [comment]
Just tested on another Fedora Server (Linux 4.1.8-200.fc22.i686+PAE):

```
# dnf copr enable mosquito/nginx
# dnf update                                       
Last metadata expiration check performed 0:06:37 ago on Mon Oct 12 02:48:17 2015.
Dependencies resolved.
=====================================================================================================================================================================================================================
 Package                                            Arch                                     Version                                                          Repository                                        Size
=====================================================================================================================================================================================================================
Installing:
 luajit                                             i686                                     2.0.3-4.fc22                                                     fedora                                           440 k
 ssdeep-libs                                        i686                                     2.13-1.fc22.remi                                                 remi                                              22 k
Upgrading:
 nginx                                              i686                                     1:1.9.5-3.modsec_2.9.0.fc22                                      mosquito-nginx                                   3.2 M
 nginx-filesystem                                   noarch                                   1:1.9.5-3.modsec_2.9.0.fc22                                      mosquito-nginx                                    20 k

Transaction Summary
=====================================================================================================================================================================================================================
Install  2 Packages
Upgrade  2 Packages

Total download size: 3.7 M
Is this ok [y/N]: y

# rpm -qR nginx | grep yajl
# libyajl.so.2
# nginx -t                                
nginx: error while loading shared libraries: libyajl.so.2: cannot open shared object file: No such file or directory
```

**Comment by 1dot75cm** [comment]
I using the default environment (Fedora Server) for test, our environment may be different. Default, System from the "/lib, /lib64" directory to search for libraries. Try to execute "ldconfig" to update the "/etc/ld.so.cache" cache.

```
# mv /lib/libyajl.so.2 /tmp/
# nginx -t
nginx: error while loading shared libraries: libyajl.so.2: cannot open shared object file: No such file or directory
# ldconfig -v | grep yajl   # create link file
  libyajl.so.2 -> libyajl.so.2.1.0 (changed)
# ldd /usr/sbin/nginx | grep yajl
    libyajl.so.2 => /lib/libyajl.so.2 (0xb7112000)
```

If your system don't search library from "/lib", please add "/lib" to "ld.so.conf" configure file. I do not know if there are other causes of this problem.

```
# echo "/lib" > /etc/ld.so.conf.d/nginx.conf
# ldconfig
```

Note: the "rpm -q --state" option don't check file's state.

```
# mv /lib/libyajl.so.2 /tmp/
# touch /lib/libyajl.so.2
# ldd /usr/sbin/nginx | grep yajl
/usr/sbin/nginx: error while loading shared libraries: /lib/libyajl.so.2: file too short
# ll /usr/lib/libyajl.so.2*
-rw-r--r--. 1 root root     0  /usr/lib/libyajl.so.2
-rwxr-xr-x. 1 root root 40064  /usr/lib/libyajl.so.2.1.0
# rpm -qls yajl
normal        /usr/bin/json_reformat
normal        /usr/bin/json_verify
normal        /usr/lib/libyajl.so.2           # error !!!!!!
normal        /usr/lib/libyajl.so.2.1.0
normal        /usr/share/doc/yajl
normal        /usr/share/doc/yajl/COPYING
normal        /usr/share/doc/yajl/ChangeLog
normal        /usr/share/doc/yajl/README
normal        /usr/share/doc/yajl/TODO
```

**Comment by black-roland** [comment]
> If your system don't search library from "/lib", please add "/lib" to "ld.so.conf" configure file. I do not know if there are other causes of this problem.

nginx works fine after yajl manual installation (`dnf install yajl`), shared libraries also ok. The issue is that yajl not installs automatically as nginx dependency.

P.S. I tested using clean enviroment (nspawn container, Linux 4.2.3-200.fc22.x86_64 and Linux 4.1.8-200.fc22.i686+PAE) and yajl installed automaticaly O_o It seems that something wrong with my VPS. I think the issue can be closed, thanks for support.

**Pull request closed without merging**
