### PR TITLE
add wiznote spec

### PR DESCRIPTION
**Pull request by 1dot75cm**
添加 wiznote-beta.spec
rpm包在 https://copr.fdzh.org/coprs/mosquito/FZUG
请社区成员审查，谢谢

### CODE REVIEW

**Comment by 1dot75cm** [comment]
额 忘记锁定了。
如果测试有bug或协议不符合等等，可以讨论/修改。

**Comment by 1dot75cm** [comment]
@alick @cheese @Endle @tvvocold

**Comment by tvvocold** [comment]
@FZUG/tier1

**Comment by sztsian** [comment]
Firstly, thanks for your hardwork.
I advise you to rebase the PR and leave only wiznote, and then make a new branch to send PR for sougoupinyin. Since your title is for wiznote. And Github can not partially merge a PR.

And I have some advise, can you add the link to [License statement](http://blog.wiz.cn/opensourceagreement.html) in wiznote spec files? It doesn't matter whether add it as comment or in description section.

**Comment by 1dot75cm** [comment]
ok i will retry.

**Pull request closed without merging**
