### PR TITLE
Update FoxitReader to 2.4.4. 

### PR DESCRIPTION
**Pull request by dengbangjie**
Bump version of FoxitReader to 2.4.4. The rpm spec was converted from archlinuxcn repo. Tested locally under fc29 gnome. I hope it could be in FZUG when fc30 is released.

### CODE REVIEW

**Comment by robberphex** [comment]
FoxitReader是专有软件，我们对其的重新分发需要获取其授权，在此附上授权文件（授权在2019年4月20日前都有效，过后需要重新和公司协商）
[FZUG（Fedora中文用户组）成员 福昕软件授权书（盖章版）2018.4.26.pdf](https://github.com/FZUG/repo/files/2683278/FZUG.Fedora.2018.4.26.pdf)

**Comment by 1dot75cm** [comment]
OK, I will check it. Thank you @dengbangjie

**Comment by dengbangjie** [comment]
My pleasure. Many thanks to all. @RobberPhex @1dot75cm and other FZUG members.

**Comment by sztsian** [comment]
Merge without testing. Thanks for the effort. Will fix if there are issues.

**Pull request merged**
