### PR TITLE
[sandbox] add spec

### PR DESCRIPTION
**Pull request by 1dot75cm**
Gentoo Sandbox tool to run programs in a "sandboxed" environment.

Homepage: https://gitweb.gentoo.org/proj/sandbox.git

```
# dnf install sandbox
$ sandbox-shell
```

please test, thanks.

### CODE REVIEW

**Comment by alick** [comment]
But is it really necessary? What is the difference and additional benefits besides:
1. `/usr/bin/sandbox` from selinux https://fedoraproject.org/wiki/Sandboxing
2. secure containers https://fedoraproject.org/wiki/Features/Securecontainers

**Comment by alick** [comment]
Ah, a side note: `sandbox -X` is broken now: https://bugzilla.redhat.com/show_bug.cgi?id=1103622
But can gentoo sandbox work with selinux enforced?

**Comment by cicku** [comment]
如果造成文件冲突，则无法合并。

**Comment by alick** [comment]
Well, there is a rename in the PR (sandbox -> sandbox-shell).

On Mon, Oct 26, 2015 at 5:21 PM, Christopher Meng
notifications@github.com wrote:

> 如果造成文件冲突，则无法合并。
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Regards,
Alick

**Comment by 1dot75cm** [comment]
> Gentoo Sandbox 与人们所熟悉的 Debian 的 "fakeroot", 和基于 RPM 的 "InstallWatch" 有
> 异曲同工的作用.

The `Gentoo Sandbox` and the `SELinux Sandbox` is different. It works fine for me.

> 如果造成文件冲突，则无法合并。

No file conflicts.

> Ah, a side note: sandbox -X is broken now: https://bugzilla.redhat.com/show_bug.cgi?id=1103622

The same problem, but it (sandbox-X) still works fine.

**Comment by alick** [comment]
Can you show me some more information about InstallWatch? Google
searches do not reveal much about it.

On Tue, Oct 27, 2015 at 4:34 AM, 1dot75cm notifications@github.com wrote:

> Gentoo Sandbox 与人们所熟悉的 Debian 的 "fakeroot", 和基于 RPM 的 "InstallWatch" 有
> 异曲同工的作用.
> 
> The Gentoo Sandbox and the SELinux Sandbox is different. It works fine for
> me.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Regards,
Alick

**Comment by 1dot75cm** [comment]
`installwatch` 是 `checkinstall` 中的工具，用于限制对 "`root`" 外文件的修改。 RHEL 5 等老版本系统，还没默认设置 `topdir`，编译时可能会更改系统配置。如果 makefile 中添加 `rm -rf /home/*/*` 之类的命令，就会有危险。这类工具就能保证编译时的系统安全。 @alick 

 http://asic-linux.com.mx/~izto/checkinstall

**Comment by cicku** [comment]
所以你们在一些古董级别的spec里经常看见第一句话%install都是

`[' %buildroot '!=' / ']`

**Pull request merged**
