### PR TITLE
Update deepin-music to 3.1.3

### PR DESCRIPTION
**Pull request by felixonmars**

### CODE REVIEW

**Comment by alick** [comment]
@1dot75cm we should drop build for fc22 and fc23, and add build for fc26

**Comment by sztsian** [comment]
The failure comes from two perspective,

> Source0: %{url}/archive/%{_commit}/%{name}-%{_shortcommit}.tar.gz

%{_shortcommit} should be %{_commit} otherwise rpmbuild will complain cannot find the source file. @felixonmars , can you change it as well? Thanks!

>  BuildRequires: deepin-tool-kit-devel

This package is not found.

**Comment by felixonmars** [comment]
Hrm, looks like deepin-tool-kit-devel should be there: https://github.com/FZUG/repo/blob/master/rpms/deepin_project/deepin-tool-kit.spec

The filename has been updated.

**Comment by sztsian** [comment]
In fact most of the packages which source contains %{_shortcommit} canot work now. I'll try to fix deepin-tool-kit shortly.

**Comment by sztsian** [comment]
It comes that the root cause is from gsettings-qt cannot be build. SPEC looks fine, but the tricky launchpad bzr download address makes things complicated.

**Comment by sztsian** [comment]
This is now blocked by https://github.com/FZUG/repo/pull/250

**Comment by sztsian** [comment]
Drop the pull request as @1dot75cm did a massive update already.

**Pull request closed without merging**
