### PR TITLE
Add Onedrive

### LINKED ISSUE #180: Package request: OneDrive
https://github.com/skilion/onedrive

I've not tested and also not verify it's license. I'll do it later

### PR DESCRIPTION
**Pull request by sztsian**
Add onedrive, fix https://github.com/FZUG/repo/issues/180 without using dmd.

### CODE REVIEW

**Comment by sztsian** [comment]
ok to test

**Comment by sztsian** [comment]
With some hack there. Including a enhancement. I've send the enhancement pull request upstream.
I uses the git source instead of stable release as the git source works better than the release in Fedora during my quick test.

**Comment by 1dot75cm** [comment]
Hi, @sztsian 
I had been review finishd. Some thing need to change. See [review.patch](https://gist.github.com/1dot75cm/95ce46b705f6a9a5038d34bacb13209f).

You need to copy and apply patch in your branch. (`patch -p1 -i review.patch`)

btw. The `DFLAGS` variable is no effect, except use `-e` option of `make` or use `make DFLAGS='-release -w -g -O3'`.

``` bash
+ export 'DFLAGS=-release -w -g -O3'
+ DFLAGS='-release -w -g -O3'
+ make -j4
ldc2 -O -release -inline -boundscheck=off -ofonedrive -L-lcurl -L-lsqlite3 -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/sqlite.d src/sync.d src/upload.d src/util.d
```

**Comment by sztsian** [comment]
Hi,
I failed to apply your patch yesterday. And I just see that you updated your comments. In fact I have some thoughts regarding this package and I will talk with you later when I have enough time.

**Comment by sztsian** [comment]
ok to test

**Comment by 1dot75cm** [comment]
ok to test

**Pull request merged**
