### PR TITLE
Initial packages

### PR DESCRIPTION
**Pull request by 1dot75cm**
提交初始软件包  
sogoupinyin, wiznote-beta, fcitx-qt5, fcitx-sunpinyin, grub4dos, bcloud, screenfetch, kwplayer, etc.

### CODE REVIEW

**Comment by tvvocold** [comment]
@FZUG/tier1

**Comment by Endle** [comment]
软件有点多啊
是否考虑拆开来提交PR？

**Comment by 1dot75cm** [comment]
> 软件有点多啊
> 是否考虑拆开来提交PR？

先这样吧，下次拆开提交

**Comment by sztsian** [comment]
I'd prefer to REJECT. Since we usually have separate concern with different packages. So I advise send PR separately.
Otherwise, all please comment in the PR and to check if any issue. We can remove the problematic package away before merge.

**Comment by 1dot75cm** [comment]
那我先关闭了？

**Pull request closed without merging**
