### PR TITLE
ue4.huge: fix strip .lib (#300)

### PR DESCRIPTION
**Pull request by alick**
Please test if this works.

### CODE REVIEW

**Comment by dengbangjie** [comment]
UE在github源代码不存在了。目前似乎需要注册才能获取代码。并且UE似乎已经不是oss了。

**Comment by alick** [comment]
@1dot75cm 源码都要注册才看得到，还能打包吗？要不删掉这个包吧

**Comment by sztsian** [comment]
既然无法直接下载源代码了，定时编译肯定也无法进行。所以我主张删掉。 @alick 你发个 PR 来删，或者 rebase 一下这个用来删掉如何？

**Comment by gbraad** [comment]
UE has never been OSS. You always needed to register to obtain a license to get access to the code. It is very dubious to even provide downloads as a packaged RPM this way, as the license grants you access and is meant to be used for modifcation to the source code to either contribute or use in your own engine. These people will likely understand what is involved and have no need for a packaged solution (and works actually against the idea).

**Comment by alick** [comment]
我另发 PR 删吧。删的话是标记 obsolete?

**Pull request closed without merging**
