### PR TITLE
index.html: fix back-top not visible at the very end (#69)

### PR DESCRIPTION
**Pull request by alick**
我简单实验了一下，感觉这样好一些。

### CODE REVIEW

**Comment by alick** [comment]
ref: #69

**Comment by 1dot75cm** [comment]
Refer to this link for build results (access rights to CI server needed): 
null/job/pr_builder/51/

**Comment by alick** [comment]
@1dot75cm Is the above comment by you or bot?

Seems to me Jenkins does not handle non-package-related commit/PR right. Please fix.

**Comment by 1dot75cm** [comment]
> Seems to me Jenkins does not handle non-package-related commit/PR right. Please fix.

OK, I fix it. You need to change this commit and force push to git repo for check jenkins configuration.

> Is the above comment by you or bot?

It's a bot.

**Pull request merged**
