### PR TITLE
update opera

### PR DESCRIPTION
**Pull request by ghost**
update opera as they are out-of-date

### CODE REVIEW

**Comment by 1dot75cm** [comment]
Refer to this link for build results (access rights to CI server needed): 
null/job/pr_builder/47/

**Comment by ghost** [comment]
@1dot75cm 话说窝觉得泥的脚本出问题了...

然后还有这个是什么鬼 :joy:  :joy: :joy:

> DEBUG: Please ignore the error above above about btrfs.

**Comment by 1dot75cm** [comment]
@nrechn  作者的小幽默 :-)))

**Comment by 1dot75cm** [comment]
Refer to this link for build results (access rights to CI server needed): 
null/job/pr_builder/48/

**Comment by 1dot75cm** [comment]
Refer to this link for build results (access rights to CI server needed): 
null/job/pr_builder/49/

**Pull request merged**
