### PR TITLE
:arrow_up: deepin-tool-kit@0.3.0

### PR DESCRIPTION
**Pull request by sztsian**
Signed-off-by: Zamir SUN <sztsian@gmail.com>

### CODE REVIEW

**Comment by sztsian** [comment]
test

**Comment by sztsian** [comment]
ok to test

**Comment by sztsian** [comment]
This is now blocked by gsettings-qt. I've filed gsettings-qt for package review in bugzilla. Once it get approved, the dependency issue can be fixed easily.
https://bugzilla.redhat.com/show_bug.cgi?id=1468665

**Comment by alick** [comment]
Maybe you can try build gsettings-qt in copr first.

**Pull request closed without merging**
