### PR TITLE
update wiznote

### PR DESCRIPTION
**Pull request by 1dot75cm**
License: https://raw.githubusercontent.com/WizTeam/WizQTClient/master/LICENSE
Update:
- wiznote-beta 更新至 2.2.1
- 解决编译错误
- 添加 icon desktop 刷新命令
- wiznote 更新至 2.1.18
- 修改版本名

### CODE REVIEW

**Comment by 1dot75cm** [comment]
@FZUG/tier1

**Comment by sztsian** [comment]
Great job. I have no issue on this.
P.S. I did not test it.

**Comment by alick** [comment]
I guess functionality tests are not required to approve the pull request,
right? What's the process of fedora official packaging?

2015-05-21 17:03 GMT+08:00 Zamir SUN notifications@github.com:

**Comment by 1dot75cm** [comment]
I want to perform software testing. The process may be "New PR -> package test [install / update / remove..] -> function test (use..) -> OK, merge PR"

**Comment by alick** [comment]
Then we need people to do the testing (like the karma mechanism in bodhi).
I remember we have recruited a volunteer team for fzug copr repo. Are they
reachable? Can they help to test?

2015-05-22 0:18 GMT+08:00 1dot75cm notifications@github.com:

**Comment by sztsian** [comment]
I think I am skilled enough in Quality Assurance. So I will try to help test it. But we need somewhere to post the test result. Is it reasonable to keep it in OpenShift?
I will just test the rpm packages in docker, not to test the spec it self, and neither do srpm.

**Comment by alick** [comment]
Thanks @sztsian . My point is we cannot rely on one person to do all package testing. A team is necessary to scale.

Besides, I am not sure what it is with OpenShift. Do you mean github issues?

**Comment by sztsian** [comment]
> Thanks @sztsian . My point is we cannot rely on one person to do all package testing. A team is necessary to scale.

Okay. And we may can send emails to the chinese list.

> Besides, I am not sure what it is with OpenShift. Do you mean github issues?

So you think just reply the test result in issue is reasonable, right?

**Comment by alick** [comment]
Yeah, I think it might be enough to use github issues. We can use :+1: :-1: to indicate it is working or not working.

**Comment by sztsian** [comment]
Ok. And I am thinking of some way to make the process automated(test the installing, and even test the spec with something like rpmlint).

**Comment by tvvocold** [comment]
https://travis-ci.org ?

**Comment by sztsian** [comment]
Backend of travis-ci seems to use Ubuntu. And so we can not handle rpm install tasks there

**Comment by 1dot75cm** [comment]
> Yeah, I think it might be enough to use github issues. We can use :+1: :-1: to indicate it is working or not working.

现 FZUG 源已迁移到 http://repo.fdzh.org ，rpm 测试可直接在 PR 中回复 (+1 release/arch)，如 +1 fc22/x86_64。如果 +1 累计 3 个以上且无 -1，则可以 merge PR。如出错需标明问题，贴上日志。

**Comment by 1dot75cm** [comment]
+1 fc22/x86_64 wiznote-beta
这款软件有成员测试了吗？我已经在 fc22/x86_64 测试通过了。
累计 3 个 +1 merge PR。

**Comment by Endle** [comment]
[**@sztsian**](https://github.com/sztsian) commented on [May 22, 2015, 1:47 PM CST](https://github.com/FZUG/repo/pull/4#issuecomment-104521052):

> Backend of travis-ci seems to use Ubuntu. And so we can not handle rpm install tasks there

How about https://drone.io/ ?
可以自定义测试用的 docker image

**Comment by 1dot75cm** [comment]
> How about https://drone.io ?
> 可以自定义测试用的 docker image

drone只能测试 包是否可以安装，对于软件功能不能测试吧？

**Pull request merged**
